development:
  adapter: postgresql
  encoding: unicode
  database: moma_app_development
  pool: 5
  host: localhost
  username: Fai
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: moma_app_test
  pool: 5
  host: localhost
  username: Fai
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: moma_app_production
  pool: 5
  host: localhost
  username: Fai
  password:
