# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45df46ace0c67579d02610b452dffdc33c23873a8e06497c79c402af3bbe4494c5967427465b74a0ffdeaf79b9824399047aedd76579456e062eb880d8d5c0d0

test:
  secret_key_base: 220a57a5a159b954d0a33187a827b3c51eaf7d117cfe9342a2bba0202df1962b00ecf41f73d0e5b00117bd397d7e5cc1c63a145ebae53ef5cedf44e602fd7199

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
